name: Déploiement sur CurseForge

permissions:
  contents: write
  pull-requests: write
  actions: write

on:
  release:
    types: [published]
  # Optionnel : déclencher aussi quand un tag est créé
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build & Publish (with data refresh)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Step 1 - Refresh SimC trinket datasets
        run: |
          echo "== Refreshing SimC Trinkets =="
          python Tools/update_simc_data.py || exit 1

      - name: Step 2 - Refresh consumables (Potions & Phials)
        run: |
          echo "== Refreshing Consumables =="
          python Tools/update_bloodmallet_consumables.py || echo "Consumables refresh encountered a non-fatal issue"

      - name: Show tag
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "Tag (from release): ${{ github.event.release.tag_name }}"
            echo "TAG_NAME=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "Tag (from push): ${{ github.ref_name }}"
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Install zip
        run: |
          sudo apt-get update
          sudo apt-get install -y zip

      - name: Generate changelog for latest tag (scoped)
        uses: tj-actions/git-cliff@8bfb7bf10268aed30bde8e34ecaeddb6c6149edd
        with:
          args: --latest
          output: LATEST_CHANGELOG.md

      - name: Copy latest → CHANGELOG.md for packager
        run: cp LATEST_CHANGELOG.md CHANGELOG.md

      - name: Run BigWigs Packager (Retail)
        uses: BigWigsMods/packager@fd8ff7f95606c6d63c9a2d4d29c06e0abf1c3a60
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
        with:
          args: -g retail

      - name: Update GitHub release body with generated changelog
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          tag_name: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref_name }}
          body_path: LATEST_CHANGELOG.md
          append_body: false
          make_latest: true
