name: Update SimCraft Data

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@d27e3f3d7c64b163f94b75078b39e7975e9b0a48 # v5
        with:
          python-version: '3.x'

      - name: Refresh SimulationCraft datasets
        run: python Tools/update_simc_data.py

      - name: Commit updates
        run: |
          if git status --short | grep -q '^ M Data/SimCraft'; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git commit -am "chore(data): refresh SimCraft trinkets"
            git push
          else
            echo "No data changes detected."
          fi
